DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS article_link;

create table types
(
	id int not null GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name varchar(255) not null,
	PRIMARY KEY (id)
);

create table articles
(
	id int not null GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name varchar(255) not null,
	typeId int not null,
	PRIMARY KEY (id),
	constraint Articles_fk
		foreign key (typeId) references types (id)
			on update cascade on delete cascade
);

create index Articles_fk
	on articles (typeId);

create table article_link
(
	article1_id int null,
	article2_id int null,
	constraint Article_Link1_fk
		foreign key (article1_id) references articles (id)
			on update cascade on delete cascade,
	constraint Article_Link2_fk
		foreign key (article2_id) references articles (id)
			on update cascade on delete cascade
)
;

create index Article_Link1_fk on article_link (article1_id);

create index Article_Link2_fk on article_link (article2_id);

